---

- name: install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - make
      - gcc
      - pkg-config
      - libssl1.0-dev
      - libreadline-dev
      - libgdbm-dev
      - zlib1g-dev
      - libyaml-dev
      - libffi-dev
      - libgmp-dev
      - openssl
  become: yes
