---

language: python
python: "2.7"
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-setuptools

env:
  - PATH=/home/travis/virtualenv/python2.7.14/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/usr/local/sbin

before_install:
  - rvm implode --force
  
  - sudo rvm implode --force

  - rm ~/.rvmrc

  - echo $PATH

install:
  - sudo -H easy_install pip
  # http://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
  - sudo -H pip install -U pyOpenSSL cryptography idna certifi
  - sudo -H pip install -U urllib3
  # https://github.com/ansible/ansible/issues/23642#issuecomment-297469043
  - sudo -H pip install -U ndg-httpsclient

  # Install ansible
  - sudo -H pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - /usr/local/bin/ruby --version

  - ls -lh /usr/local/bin

  - ls -la ~

  - which bundle

  - bundle --version

  - /usr/local/bin/bundle --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
