---

#- name: update gem
#  command: gem update --system
#  become: yes

- name: install gems
  command: gem install --no-user-install --quiet --bindir /usr/local/bin {{ item.name }} -v {{ item.version }}
  with_items:
    - name: bundler
      version: 1.17.3
  become: yes
